=== opendata/Hunting-and-Fishing/schemas/1.0a/hunting.json
{
	"type":"object",
	"title":"hunting",
	"$schema": "http://json-schema.org/draft-04/schema",
	"properties":{
		"agency": {
			"type":"string"
		},
		"date_effective": {
			"type":"string",
			"format":"date-time"
		},
		"date_expires": {
			"type":"string",
			"format":"date-time"
		},
		"documentation": {
			"type":"string",
			"format":"uri"
		},
		"schema_version": {
			"type":"string"
		},
		"conformsTo": {
			"type":"string",
			"format":"uri"
		},
		"state": {
			"type":"string",
			"minLength":2,
			"maxLength":2,
			"pattern":"([A-Z]{2})"
		},
		"seasons": {
			"type":"object",
			"properties":{
				"season": {
					"type":"object",
					"properties":{
						"name": {
							"type":"string"
						},
						"comment": {
							"type":"string"
						},
						"method_rules": {
							"type":["string", "array"],
							"items": {
								"type":"string"
							},
							"required": ["items"]
						},
						"method": {
							"type": ["string", "array"]
						},
						"range": {
							"type":"array",
							"properties":{
								"1": {
									"type":"object",
									"properties":{
										"places": {
											"type":"object"
										},
										"season": {
											"type":"object",
											"properties":{
												"date": {
													"type":"object",
													"properties":{
														"ends": {
															"type":"string"
														},
														"starts": {
															"type":"string"
														}
													}
												}
											}
										}
									}
								}
							}
						}
					},
					"required":["method"]
				}
			},
			"required":["season"]
		},
		"species": {
			"type":"object",
			"properties":{
				"name": {
					"type":"string"
				},
				"bova_id": {
					"type":"string"
				},
				"taxonomy": {
					"type":"string"
				},
				"url": {
					"type":"string",
					"format":"uri"
				},
				"aliases": {
					"type":"array"
				},
				"members": {
					"type":"array",
					"properties":{
						"name": {
							"type":"string"
						},
						"bova_id": {
							"type":"string"
						},
						"taxonomy": {
							"type":"string"
						},
						"url": {
							"type":"string",
							"format":"uri"
						},
						"aliases": {
							"type":"array"
						}
					},
					"required":["name"]
				}
			},
			"required":["name"]
		}
	},
	"required": ["agency", "date_effective", "date_expires", "documentation", "schema_version", "conformsTo", "state", "seasons"]
}

=== opendata/Hunting-and-Fishing/hunting/pheasant.json
{
	"state": "VA",
	"agency": "Department of Game and Inland Fisheries",
	"date_effective": "2014-07-01T00:00:00-05:00",
	"date_expires": "2015-06-30T23:59:59-05:00",
	"conformsTo": "https://raw.githubusercontent.com/opendata/Hunting-and-Fishing/master/schemas/1.0a/hunting.json",
	"schema_version": "1.0a",
	"documentation": "http://rooseveltschema.org/",
	"species": {
		"name": "pheasant",
		"aliases": ["common pheasant", "ring-necked pheasant"],
		"taxonomy": "Phasianus colchicus",
		"bova_id": "40101",
		"url": "http://www.dgif.virginia.gov/hunting/regulations/smallgame.asp"
	},
	"seasons": {
		"season": {
			"method": ["modern firearms", "muzzleloading firearms", "archery tackle"],
			"range": [
				{
					"places": {
						"Virginia": {
							"gnis_id": 1779803,
							"fips_code": 51
						}
					},
					"season": {
						"date": {
							"starts": "2014-11-08",
							"ends": "2015-01-31"
						}
					}
				}
			]
		}
	}
}

=== opendata/Hunting-and-Fishing/hunting/quail.json
{
	"state": "VA",
	"agency": "Department of Game and Inland Fisheries",
	"date_effective": "2014-07-01T00:00:00-05:00",
	"date_expires": "2015-06-30T23:59:59-05:00",
	"conformsTo": "https://raw.githubusercontent.com/opendata/Hunting-and-Fishing/master/schemas/1.0a/hunting.json",
	"schema_version": "1.0a",
	"documentation": "http://rooseveltschema.org/",
	"species": {
		"name": "quail",
		"aliases": ["northern bobwhite", "Virginia quail", "bobwhite quail"],
		"taxonomy": "Colinus virginianus",
		"bova_id": "40100",
		"url": "http://www.dgif.virginia.gov/quail/"
	},
	"seasons": {
		"season": {
			"method": ["modern firearms", "muzzleloading firearms", "archery tackle"],
			"range": [
				{
					"places": {
						"Virginia": {
							"gnis_id": 1779803,
							"fips_code": 51
						}
					},
					"season": {
						"date": {
							"starts": "2014-11-08",
							"ends": "2015-01-31"
						}
					}
				}
			],
			"bag_limit": "Six per day."
		}
	}
}

=== opendata/Hunting-and-Fishing/hunting/opossum.json
{
	"state": "VA",
	"agency": "Department of Game and Inland Fisheries",
	"date_effective": "2014-07-01T00:00:00-05:00",
	"date_expires": "2015-06-30T23:59:59-05:00",
	"conformsTo": "https://raw.githubusercontent.com/opendata/Hunting-and-Fishing/master/schemas/1.0a/hunting.json",
	"schema_version": "1.0a",
	"documentation": "http://rooseveltschema.org/",
	"species": {
		"name": "opossum",
		"aliases": ["possum"],
		"taxonomy": "Didelphis virginiana",
		"bova_id": "50001",
		"url": "http://www.dgif.virginia.gov/wildlife/information/?s=050001"
	},
	"seasons": {
		"season": {
			"method": "firearm",
			"range": [
				{
					"places": {
						"Virginia": {
							"gnis_id": 1779803,
							"fips_code": 51
						}
					},
					"season": {
						"date": {
							"starts": "2014-10-10",
							"ends": "2015-03-10"
						}
					}
				},
				{
					"places": {
						"any city": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"any town": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Arlington": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Chesterfield": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Fairfax": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Henrico": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"James City": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Loudoun": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Prince William": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Spotsylvania": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Stafford": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"Roanoke": {
							"gnis_id": "TK",
							"fips_code": "TK"
						},
						"York": {
							"gnis_id": "TK",
							"fips_code": "TK"
						}
					},
					"season": {
						"date": {
							"starts": "2014-07-01",
							"ends": "2015-06-30"
						}
					}
				}
			]
		}
	}
}

=== opendata/Hunting-and-Fishing/hunting/weasel.json
{
	"state": "VA",
	"agency": "Department of Game and Inland Fisheries",
	"date_effective": "2014-07-01T00:00:00-05:00",
	"date_expires": "2015-06-30T23:59:59-05:00",
	"conformsTo": "https://raw.githubusercontent.com/opendata/Hunting-and-Fishing/master/schemas/1.0a/hunting.json",
	"schema_version": "1.0a",
	"documentation": "http://rooseveltschema.org/",
	"species": {
		"name": "weasel",
		"members": [
			{
				"name": "least weasel",
				"taxonomy": "Mustela nivalis allegheniensis",
				"bova_id": "50040",
				"url": "http://www.dgif.virginia.gov/wildlife/information/?s=050040"
			},
			{
				"name": "long-tailed weasel",
				"taxonomy": "Mustela frenata noveboracensis",
				"bova_id": "50041",
				"url": "http://www.dgif.virginia.gov/wildlife/information/?s=050041"
			}
		]
	},
	"seasons": {
		"season": {
			"method": "traps",
			"range": [
				{
					"places": {
						"Virginia": {
							"gnis_id": 1779803,
							"fips_code": 51
						}
					},
					"season": {
						"date": {
							"starts": "2014-12-01",
							"ends": "2015-02-28"
						}
					}
				}
			]
		}
	}
}

=== opendata/Hunting-and-Fishing/hunting/squirrel.json
{
	"state": "VA",
	"agency": "Department of Game and Inland Fisheries",
	"date_effective": "2014-07-01T00:00:00-05:00",
	"date_expires": "2015-06-30T23:59:59-05:00",
	"conformsTo": "https://raw.githubusercontent.com/opendata/Hunting-and-Fishing/master/schemas/1.0a/hunting.json",
	"schema_version": "1.0a",
	"documentation": "http://opendata.github.io/Hunting-and-Fishing/",
	"species": {
		"name": "squirrel",
		"members": [
			{
				"name": "eastern gray squirrel",
				"taxonomy": "Sciurus carolinensis carolinensis",
				"bova_id": 50057,
				"url": "http://www.dgif.virginia.gov/wildlife/information/?s=050057"
			},
			{
				"name": "red squirrel",
				"taxonomy": "Tamiasciurus hudsonicus abieticola",
				"bova_id": 50060,
				"url": "http://www.dgif.virginia.gov/wildlife/information/?s=050060"
			},
			{
				"name": "fox squirrel",
				"comment": "there are four kinds of fox squirrels -- which one do we want?",
				"taxonomy": "??????",
				"bova_id": "TK",
				"url": "TK"
			}
		]
	},
	"seasons": {
		"season": {
			"method": ["traps", "modern firearms", "muzzleloading firearms", "archery tackle"],
			"range": [
				{
					"places": {
						"Virginia": {
							"gnis_id": 1779803,
							"fips_code": 51
						}
					},
					"season": {
						"date": {
							"starts": "2014-09-06",
							"ends": "2015-02-28"
						}
					}
				}
			],
			"comment": "Gray and red squirrels only."
		},
		"season": {
			"method": ["traps", "modern firearms", "muzzleloading firearms", "archery tackle"],
			"range": [
				{
					"places": {
						"Virginia": {
							"gnis_id": 1779803,
							"fips_code": 51
						}
					},
					"season": {
						"date": {
							"starts": "2014-09-06",
							"ends": "2015-01-31"
						}
					}
				}
			],
			"comment": "Fox squirrels only."
		},
		"season": {
			"method": ["traps", "modern firearms", "muzzleloading firearms", "archery tackle"],
			"range": [
				{
					"places": {
						"Virginia": {
							"gnis_id": 1779803,
							"fips_code": 51
						}
					},
					"exceptions": {
						"National Forest lands": {}
					},
					"season": {
						"date": {
							"starts": "2015-06-06",
							"ends": "2015-06-20"
						}
					}
				}
			]
		},
		"bag_limit": "All squirrels combinedâ€”six per day.",
		"comment": "Gray and red squirrels may be harvested statewide, unless otherwise posted, and on the following wildlife management areas: Amelia, Big Survey, Big Woods, Briery Creek, Cavalier, Chickahominy, Dick Cross, Doe Creek, Fairystone (including Fairystone State Park and Philpott Reservoir), Featherfin, Gathright, Goshen, Hardware River, Havens, Highland, Hog Island (Carlisle Tract only), Horsepen, James River, Lake Robertson, Little North Mountain, Mattaponi, Merrimac Farm, Pettigrew, Phelps, Powhatan (including the Goochland Tract), Rapidan, Short Hills, Stewarts Creek, G. Richard Thompson, Turkeycock Mountain, and White Oak Mountain. Fox squirrels may be harvested on all lands, unless otherwise posted, in all counties with an open fox squirrel season during the fall squirrel season and on the following wildlife management areas: Big Survey, Gathright, Goshen, Havens, Highland, Lake Robertson, Little North Mountain, Merrimac Farm, Phelps, Rapidan, Short Hills, Stewarts Creek, and G. Richard Thompson."
	}
}
